# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

mod_id=autoclicker

# Mod properties
mod_version = 26.3.0.1
maven_group = pro.mikey.mods
archives_base_name = autoclicker

# Minecraft properties
minecraft_version = 26.3
minecraft_version_range_mvn=[26.3,27)
minecraft_version_range_sem=>=26.3.0
supported_minecraft_versions = 26.3

# Dependencies
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
fabric_api_version_range=>=0.161.0+26.3

neoforge_version = 26.3.0.7-beta
neoforge_version_range=[26.3.0.0,)

modmenu = 20.0.0-beta.4

curseforge_id=445095
modrinth_id=r8axuw4u
