pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://files.minecraftforge.net/maven/" }
        maven { url "https://maven.nanite.dev/releases" }
    }
}

rootProject.name = 'autoclicker'

include 'common'
include 'fabric'
include 'neoforge'
