modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/advancedxray/auto-clicker/issues"
license = "MIT"

[[mods]]
modId = "autoclicker"
version = "${version}"
displayName = "Auto Clicker"
authors = "ErrorMikey"
description = '''
Automatically left and right clicks for you, how kind!
'''
logoFile = "assets/autoclicker-fabric/icon.png"

[[dependencies.autoclicker]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autoclicker]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "autoclicker.mixins.json"
