modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/advancedxray/auto-clicker/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Auto Clicker"
authors = "ErrorMikey"
description = '''
Automatically left and right clicks for you, how kind!
'''
logoFile = "assets/autoclicker-fabric/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range_mvn}"
ordering = "NONE"
side = "BOTH"
