name: Release

on:
  push:
    tags:
      - "v*"
      -
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: 25
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run gradle tasks
        env:
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
          CURSE_TOKEN: ${{ secrets.CURSE_DEPLOY_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publish publishMods --no-daemon
