name: CI Build & Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
        if: github.ref != 'refs/heads/1.16'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        if: github.ref == 'refs/heads/1.16'
      - name: Build with Gradle
        env:
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon
      - name: Release to CurseForge
        if: |
          !contains(github.event.head_commit.message, '[norelease]')
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          CURSE_DEPLOY_TOKEN: ${{ secrets.CURSE_DEPLOY_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build curseforge --stacktrace --no-daemon