name: CI Build & Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 & Cache
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Release
        if: |
          !contains(github.event.head_commit.message, '[norelease]')
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          CURSE_DEPLOY_TOKEN: ${{ secrets.CURSE_DEPLOY_TOKEN }}
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build publish publishMods --stacktrace --no-daemon
